---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Sumana Srivatsa"
keywords:    "sumana srivatsa, causal inference, computational biology"
description: "This is Sumana's personal page."
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  green1:    '#C5EB8E'
  green2:    '#A8DBA8'
  #green3:    '#79BD9A'
  green4:    '#3B8686'
  green5:    '#0B486B'
  #blue:      '#49a7e9'
  #green:     '#9bcf2f'
  #purple:    '#c869bf'
  #orange:    '#fab125'
  #turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

